/// Map a 6-bit value to its UU-encoded character.
///
/// Zero encodes as backtick (0x60) to avoid trailing-space stripping by mail
/// relays; all other values encode as `v + 32`.
#[inline]
fn encode_char(v: u8) -> u8 {
    if v == 0 {
        0x60 // backtick
    } else {
        v + 32
    }
}

/// Encode `data` as a UU block with the given `filename` and Unix `mode`.
///
/// Returns the complete encoded block as a byte vector including `begin` and
/// `end` lines.
pub fn encode(data: &[u8], filename: &str, mode: u32) -> Vec<u8> {
    let mut out = Vec::new();

    // begin line
    out.extend_from_slice(format!("begin {:03o} {}\n", mode, filename).as_bytes());

    // data lines: one per 45-byte chunk
    for chunk in data.chunks(45) {
        // length character
        out.push((chunk.len() as u8) + 32);

        // encode groups of 3 bytes → 4 chars, padding last group if needed
        let mut i = 0;
        while i < chunk.len() {
            let b0 = chunk[i];
            let b1 = if i + 1 < chunk.len() { chunk[i + 1] } else { 0 };
            let b2 = if i + 2 < chunk.len() { chunk[i + 2] } else { 0 };

            let a = b0 >> 2;
            let b = ((b0 & 0x03) << 4) | (b1 >> 4);
            // top 2 bits of b2 fill the low 2 bits of c (b2>>6, not b2>>2)
            let c = ((b1 & 0x0F) << 2) | (b2 >> 6);
            // bottom 6 bits of b2 (not 2)
            let d = b2 & 0x3F;

            out.push(encode_char(a));
            out.push(encode_char(b));
            out.push(encode_char(c));
            out.push(encode_char(d));

            i += 3;
        }

        out.push(b'\n');
    }

    // terminator line
    out.push(0x60); // backtick
    out.push(b'\n');

    // end line
    out.extend_from_slice(b"end\n");

    out
}

#[cfg(test)]
mod tests {
    use super::encode;

    // Oracle values generated by the reference Python implementation using
    // backtick (0x60) for zero-valued 6-bit groups, matching this crate's
    // encode_char() contract.
    //
    // Python script used:
    //   def encode_char_backtick(v):
    //       return 0x60 if v == 0 else v + 32
    //   def uu_encode_chunk(chunk): ...  (see bead MIME-ksl.3 description)

    #[test]
    fn encode_cat() {
        // b"Cat" → b'begin 644 test.txt\n#0V%T\n`\nend\n'
        // Oracle: Python uu_encode(b"Cat") with correct b2>>6 and d=b2&0x3F
        let expected = b"begin 644 test.txt\n#0V%T\n`\nend\n";
        assert_eq!(encode(b"Cat", "test.txt", 0o644), expected);
    }

    #[test]
    fn encode_empty() {
        // Empty data: no data lines, just begin / backtick / end
        let expected = b"begin 644 empty\n`\nend\n";
        assert_eq!(encode(b"", "empty", 0o644), expected);
    }

    #[test]
    fn encode_45_bytes_aligned() {
        // bytes(range(45)) — exactly one data line
        let data: Vec<u8> = (0u8..45).collect();
        let result = encode(&data, "test.txt", 0o644);

        // Oracle hex: Python uu_encode(bytes(range(45))) with correct b2>>6, d=b2&0x3F
        let expected = hex_decode(
            "626567696e2036343420746573742e7478740a\
             4d606024226050302521403c282230482b2360542e2351603124412c\
             34253138372621443a2651503d27415c402832284329223446295240\
             492a424c4c\
             0a600a656e640a",
        );
        assert_eq!(result, expected);

        // Must have exactly one data line between begin and terminator
        let lines: Vec<&[u8]> = result.split(|&b| b == b'\n').collect();
        // lines: [begin, data, `, end, ""]
        assert_eq!(lines.len(), 5, "unexpected line count: {:?}", lines.len());
        assert!(
            lines[1].starts_with(&[b'M']),
            "length char should be 'M' (45+32=77=0x4d='M')"
        );
    }

    #[test]
    fn encode_46_bytes_two_lines() {
        // bytes(range(46)) — two data lines
        let data: Vec<u8> = (0u8..46).collect();
        let result = encode(&data, "test.txt", 0o644);

        // Oracle hex: Python uu_encode(bytes(range(46))) with correct b2>>6, d=b2&0x3F
        let expected = hex_decode(
            "626567696e2036343420746573742e7478740a\
             4d606024226050302521403c282230482b2360542e2351603124412c\
             34253138372621443a2651503d27415c402832284329223446295240\
             492a424c4c\
             0a212b3060600a600a656e640a",
        );
        assert_eq!(result, expected);

        let lines: Vec<&[u8]> = result.split(|&b| b == b'\n').collect();
        // lines: [begin, data_line1, data_line2, `, end, ""]
        assert_eq!(lines.len(), 6, "expected 6 entries after split");
    }

    #[test]
    fn encode_mode_zero() {
        let result = encode(b"Cat", "test.txt", 0);
        assert!(result.starts_with(b"begin 000 test.txt\n"));
    }

    #[test]
    fn encode_mode_755() {
        let result = encode(b"Cat", "test.txt", 0o755);
        assert!(result.starts_with(b"begin 755 test.txt\n"));
    }

    #[test]
    fn encode_filename_verbatim() {
        // Filename with spaces and special chars — no validation, passed through
        let result = encode(b"x", "my file.bin", 0o600);
        assert!(result.starts_with(b"begin 600 my file.bin\n"));
    }

    #[test]
    fn encode_ends_with_end_newline() {
        let result = encode(b"hello", "f", 0o644);
        assert!(result.ends_with(b"end\n"));
    }

    #[test]
    fn encode_terminator_line_present() {
        // The line before "end\n" must be backtick-newline
        let result = encode(b"hello", "f", 0o644);
        assert!(result.ends_with(b"`\nend\n"));
    }

    #[test]
    fn roundtrip_encode_decode() {
        let encoded = super::encode(b"hello world", "f.bin", 0o644);
        let decoded = crate::decode(&encoded).unwrap();
        assert_eq!(decoded.data, b"hello world");
        assert_eq!(decoded.metadata.filename, "f.bin");
        assert_eq!(decoded.metadata.mode, 0o644);
        assert!(!decoded.is_truncated);
    }

    /// Decode a hex string (whitespace ignored) to bytes.
    fn hex_decode(s: &str) -> Vec<u8> {
        let s: String = s.chars().filter(|c| !c.is_whitespace()).collect();
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
            .collect()
    }
}
